name: Test DataProf Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test DataProf Action
      uses: ./
      with:
        file_path: examples/sample_data.csv
        output_format: json
        save_profile: true