name: Test DataProf Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test DataProf Action
      uses: ./
      with:
        file: examples/sample_data.csv
        output-format: json
        ml-threshold: 70